version: '3.7'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
    ports:
      - 3000:3000

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    ports:
      - 5000:5000
    depends_on:
      - client

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./client/dist:/usr/share/nginx/html
    ports:
      - 80:80
    depends_on:
      - client
      - backend
    restart: always